### ISSUE TITLE
*.js *.js6 and *.js~ files

### ISSUE THREAD

**Issue by mtscout6** [theamazingfedex/tdd_extw#6]
Seems to me that *.js files are generated and shouldn't be committed.

*.js~ seem to be editor temp files that shouldn't be committed.

*.js6 file extension is not very future proof for when es7 comes out.

**Comment by theamazingfedex** [comment]
*.js files are the actual running components of the package. Babel transpiles the package from es6 to es5, and the es5 application is what is symlinked. If someone were to clone the repo, they would need to run the babeller script before being able to launch, so that is why I include the .js files.

I'll try removing .js6~ again.

That is a good point, I will update the extension from *.js6 to *.jsx

**Comment by mtscout6** [comment]
*.jsx is something else entirely. Stick with *.js and compile the results to a different directory.
